### ISSUE TITLE
more key info on status mouse-over

### ISSUE THREAD

**Issue by ralfhauser** [gpoltera/XClavis#12]
as an extension of #6 , on mouse-over, show also
- key length/entropy
- first use date
- what/first activity: encryption/decryption

**Comment by gpoltera** [comment]
Added in Version 0.105.
Link to commit: https://github.com/gpoltera/XClavis/commit/bf8099d611225b80febca47342a71b0ebfe27644
ATTENTION: Please delete KeyStore created on a previous version!!
