### ISSUE TITLE
Additional use-case: key for pdf-decryption

### ISSUE THREAD

**Issue by ralfhauser** [gpoltera/XClavis#8]
1) a small java library to create a QR (plus some max 70 char initial comment line) from an AES 128/256 key
2) copy key to clipboard (and ignore the initial comment line) on the receiving side.

Pls contact PrivaSphere re this  (cPdf use case)

**Comment by gpoltera** [comment]
Added in Version 0.103.
Link to commits: https://github.com/gpoltera/XClavis/commit/09b34b78d898216a9d7667e70435354d8511cb60 https://github.com/gpoltera/XClavis/commit/76f43f3f599536b4af8a9d4aa89bd5486b909881 https://github.com/gpoltera/XClavis/commit/d365dba085b57a7cec7a8b585f0110b7186cdbfb
